### ISSUE TITLE
Logo on Github Dark Background

### ISSUE THREAD

**Issue by SirNate0** [u3d-community/U3D#19]
The present logo does not work well on a dark background. E.g. 
![image](https://user-images.githubusercontent.com/10181610/204644578-3c59f272-45bd-4bae-847c-64faeeb2c607.png)

It stands out better with a light stroke applied to it, though I'm not sure that I'd say it looks better. I will leave it to the artists to figure out.

![u3d](https://user-images.githubusercontent.com/10181610/204644992-0933b4b8-d120-4a13-8415-67b9ace12c28.svg)

**Comment by klaussilveira** [comment]
Ah, good catch. We can probably use the internal version of the logo: https://github.com/u3d-community/U3D/blob/master/bin/Data/Textures/Logo.png or https://github.com/u3d-community/U3D/blob/master/bin/Data/Textures/FishBoneLogo.png

**Comment by klaussilveira** [comment]
Fixed.
