### ISSUE TITLE
Can not import 3d model with multiple materials

### ISSUE THREAD

**Issue by alexefu73** [u3d-community/U3D#41]
Hi gurus,
I started to learn programming games with the great framework U3D (Urho3D), and in progress of learning the engine I faced some problems.  And searched the whole web for the solution, and no luck.

I exported 3D scene made in Blender to .obj, then imported to the U3D Editor.sh.  Every thing looks good but the shadows not exactly what I expect to look, but that's not the serious problem I faced.  Then saved the file.

The big and serious problem is when imported it to U3D it's look like couldn't find other than one of the material files or the textures exported with it.

Here is the scene I made in Blender:
![Scene in Blender](https://user-images.githubusercontent.com/62205972/224022385-96728140-9452-422e-88a6-85b62f89786f.png)

And here is when imported to the U3D Editor.sh, every thing in place, but the shadows not settled as it in blender:
![Scene in Urho3D Editor sh ](https://user-images.githubusercontent.com/62205972/224023035-13ed8426-314a-43a1-9c57-2cbf4d9acf63.png)

And eventually here is what the scene look when imported the my app, there is just one material with it's texture image for all the objects in the scene:
![Scene after Urho3D](https://user-images.githubusercontent.com/62205972/224023443-13878980-3d31-49bc-9156-3b024b694648.png)

And here is the code I used to create the scene and imported materials:
////////////////////////////////////////////////////////////////////////////////
// (4-1) Create sci-fi scene static model
    {
        scifi = scene_->CreateChild("scifiPlanet");
        //scifi->SetPosition(Vector3(-1, 1.6, -3));
        scifi->SetPosition(Vector3::ZERO);
        scifi->Scale(1);

        StaticModel* object = scifi->CreateComponent<StaticModel>();
        object->SetModel(cache->GetResource<Model>("Models/Sci-fi.mdl"));
        object->SetMaterial(cache->GetResource<Material>("Materials/Corridor_ways_mat.xml"));
        object->SetCastShadows(true);

        RigidBody* scifiBody = scifi->CreateComponent<RigidBody>();
        scifiBody->SetCollisionLayer(2);

        CollisionShape* shape = scifi->CreateComponent<CollisionShape>();
        shape->SetBox(Vector3::ONE);
    }
////////////////////////////////////////////////////////////////////////////////

So, where is the wrong here.  What mistake I did in the code please?

**Comment by SirNate0** [comment]
As to the shadows, Blender will do a better job of shadows (especially with the Rendered view), as it's meant for rendering videos and such ahead-of-time, and not necessarily real-time. Urho's shadows typically have hard edges, though there was [some work to get soft shadows working](https://discourse-urho3d.github.io/t/rendering-improvements-wip/2052/). Possibly others have more info on that.

**Comment by alexefu73** [comment]
> ```c++
>     object->SetMaterial(cache->GetResource<Material>("Materials/Corridor_ways_mat.xml"));
> ```
> 
> You are only loading one material, so you only see one material. Add the material index before the material in [SetMaterial](https://u3d.io/docs/class_urho3_d_1_1_static_model.html#a132f9e9f69f0c0b5b5f6a88cf8779a26) to add more than one.
> 
> Exporter-wise, there is also a Blender->Urho3D exporter plugin, which can also create an XML file that you load as a node with all the materials and such setup properly for you (though you will have to use an older version of Blender, <2.8, or use the newer versions but use special Materials that the exporter recognizes to map to Urho's materials).

Thank you so much.  This is really the reason to not show the other materials, but could you add this information to the wiki, because it's not intuitive to do this trick.

Secondly, I'm now doing that by 'try, check and correct' way for each model to set its material, but because the scene contain much models it's hard to keep going using this way, so is there a way to know the index of each model and its material.

**Comment by alexefu73** [comment]
Ok. It's done now.  I follow the instructions in https://discourse-urho3d.github.io/t/how-would-i-use-blender-to-load-a-model-with-more-than-one-material/6824/, and made the following modifies to the code as follows:

////////////////////////////////////////////////////////////////

StaticModel* object = scifi->CreateComponent<StaticModel>();
object->SetModel(cache->GetResource<Model>("Models/Sci-fi.mdl"));
object->ApplyMaterialList("Models/Sci-fi.txt");

////////////////////////////////////////////////////////////////////////////

The materials is in it their's places correctly.

![Screenshot_20230311_111224](https://user-images.githubusercontent.com/62205972/224473274-4d8a8c49-cc78-4a69-a23f-67f0b66a7700.png)
