### ISSUE TITLE
Migrate String Formating to fmt

### ISSUE THREAD

**Issue by SirNate0** [u3d-community/U3D#9]
I much prefer the [fmt](https://fmt.dev/latest/index.html) library's style of formatting with `{}` over the traditional printf style formatting with `%s`, `%d`, `%f`, etc. Mainly it's not an issue, as there's already some code I use to add it to Urho, but all of the formatted log macros like URHO3D_LOGDEBUGF use the printf style.

Rather than directly replacing them, an alternative would be something like URHO3D_LOGDEBUGFMT, but that is a really long name. If we're fine with some breaking changes, I would prefer renaming the old one, possibly to something like URHO3D_LOGDEBUGX, and use URHO3D_LOGDEBUGF for the fmt-style formatting.

**Comment by klaussilveira** [comment]
Can we add code in for `URHO3D_LOGDEBUGFMT`, add deprecation warnings for `URHO3D_LOGDEBUGX` and then in `2.0` fully rename?

This way we make it clear that from `1.x` to `2.x`, changes will be necessary. We can also start maintaining an `UPGRADE.md` document with how to move from `1.x` to `2.x`.

**Comment by SirNate0** [comment]
That sounds acceptable to me. I will work on a PR to add the macros. Should I change all the engine code to use the new macros as well? (It's not that hard, I'm pretty sure, just a little regex magic to replace all the format strings). Or just add the macros and a separate one to change the use in the engine?

Broader question, which I opened as issue #14, is whether we want to shorten URHO3D to U3D in the macro? I think we should, as then even with the addition of MT to the macros they are shorter by a letter, and shorter by 3 letters for 2.x.

**Comment by klaussilveira** [comment]
I think changing the existing engine code might be good to endorse the new library. I also believe it fits the original architectural guideline of Urho: letting well known libraries to the heavy lifting. :+1:
